keys:
  - &house age1rkk2ppzv60u54zalcwgzn4cw2zeemtpd7ndydm4wtzhhjz50gers9xygtp
  - &builder age15nqvv96d8tgulr0laun3dpp7kmj8ysnm7953mk34c7mylhlu5pms9x4smx
  - &m1_base age1mh6zszpgypkhethjkajy2wa8qdm7759d5sw2d3ce68vt03lweeqqvacce8
creation_rules:
  - key_groups:
      - age:
          - *house
          - *builder
          - *m1_base
