keys:
  - &house age1rkk2ppzv60u54zalcwgzn4cw2zeemtpd7ndydm4wtzhhjz50gers9xygtp
  - &m1_base age1mh6zszpgypkhethjkajy2wa8qdm7759d5sw2d3ce68vt03lweeqqvacce8
creation_rules:
  - key_groups:
      - age:
          - *house
          - *m1_base
